# THE FOLLOWING ACTIONS CODE IS FROM THE PSYCH ENGINE REPO: https://github.com/ShadowMario/FNF-PsychEngine/blob/main/.github/workflows/main.yml

name: Build

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildWindows:
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4.1.7

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4
      - name: Setup Haxe Path
        run: |
          setx HAXEPATH "C:\HaxeToolkit\haxe"
          setx PATH "%HAXEPATH%;%PATH%"
      # Runs a set of commands using the runners shell
      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          haxelib git flixel https://github.com/T5mpler/flixel-dnb f2dc7ba3b7c3fc3fcb4991577571c3dfc4f51cae
          haxelib git flixel-addons https://github.com/T5mpler/flixel-addons-dnb 75a25a3adfe6c50690444e3af54cc0ed341b3274
          haxelib git openfl https://github.com/T5mpler/openfl-dnb 74d8f72890b9ae70bba589d034ea35b86588e548
          haxelib git lime https://github.com/T5mpler/lime-dnb adb5f5c5e7fe73b5ff666f3d66fc0501b385d84e
          haxelib install hxvlc
          haxelib install hxdiscord_rpc 1.3.0
          haxelib git hxcpp https://github.com/ShadowEngineTeam/hxcpp main
          haxelib install format
          haxelib install hxp
          haxelib git grig.audio https://gitlab.com/haxe-grig/grig.audio.git main src
          haxelib git funkin.vis https://github.com/T5mpler/funkVis-dnb.git main
          haxelib git flixel-animate https://github.com/MaybeMaru/flixel-animate.git aae07578e60a83347e8189af1b312d69d05215b8
          haxelib git hscript https://github.com/T5mpler/hscript-dnb.git dfa1f291224942a585e412fd0a2d3b14e1370980
          haxelib git polymod https://github.com/T5mpler/polymod-dnb.git
          haxelib git json2object https://github.com/FunkinCrew/json2object a8c26f18463c98da32f744c214fe02273e1823fa
          haxelib git thx.core https://github.com/fponticelli/thx.core.git master
          haxelib git jsonpatch https://github.com/EliteMasterEric/jsonpatch f9b83215acd586dc28754b4ae7f69d4c06c3b4d3
          haxelib git jsonpath https://github.com/EliteMasterEric/jsonpath 7a24193717b36393458c15c0435bb7c4470ecdda
          haxelib list
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile
        run: haxelib run lime build windows --app-version="4.0.0-${{ github.run_id}}"
      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windowsBuild
          path: export/release/windows/bin
